# Sorting and Ranking in Pandas

This notebook demonstrates sorting values and indexes, null placement, ranking ties, group ranking, top-N selection, and ordered categories.

In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)
df = pd.DataFrame({
    'name': ['Asha', 'Ravi', 'Meera', 'Kabir', 'Zoya', 'Ishan'],
    'department': ['IT', 'Sales', 'IT', 'Sales', 'HR', 'IT'],
    'score': [88, 74, 95, 74, 91, 88],
    'experience': [3, 5, 2, 7, 4, 1],
    'city': ['Indore', 'Pune', 'Indore', 'Delhi', 'Pune', 'Delhi']
})
df

    name department  score  experience    city
0   Asha         IT     88           3  Indore
1   Ravi      Sales     74           5    Pune
2  Meera         IT     95           2  Indore
3  Kabir      Sales     74           7   Delhi
4   Zoya         HR     91           4    Pune
5  Ishan         IT     88           1   Delhi

## 1. Sort one column

In [2]:
df.sort_values('score')

    name department  score  experience    city
1   Ravi      Sales     74           5    Pune
3  Kabir      Sales     74           7   Delhi
0   Asha         IT     88           3  Indore
5  Ishan         IT     88           1   Delhi
4   Zoya         HR     91           4    Pune
2  Meera         IT     95           2  Indore

In [3]:
df.sort_values('score', ascending=False)

    name department  score  experience    city
2  Meera         IT     95           2  Indore
4   Zoya         HR     91           4    Pune
5  Ishan         IT     88           1   Delhi
0   Asha         IT     88           3  Indore
1   Ravi      Sales     74           5    Pune
3  Kabir      Sales     74           7   Delhi

## 2. Sort by multiple columns

In [4]:
df.sort_values(['department', 'score'], ascending=[True, False])

    name department  score  experience    city
4   Zoya         HR     91           4    Pune
2  Meera         IT     95           2  Indore
0   Asha         IT     88           3  Indore
5  Ishan         IT     88           1   Delhi
1   Ravi      Sales     74           5    Pune
3  Kabir      Sales     74           7   Delhi

## 3. Case-insensitive sorting

In [5]:
names = pd.DataFrame({'name': ['zoya', 'Asha', 'meera', 'RAVI']})
names.sort_values('name', key=lambda s: s.str.lower())

    name
1   Asha
2  meera
3   RAVI
0   zoya

## 4. Missing values and index sorting

In [6]:
missing = pd.DataFrame({'item': ['A', 'B', 'C'], 'score': [80, None, 95]})
print('Missing first:')
display(missing.sort_values('score', na_position='first'))
print('Missing last:')
display(missing.sort_values('score', na_position='last'))

Missing first:

  item  score
1    B    NaN
0    A   80.0
2    C   95.0

Missing last:

  item  score
0    A   80.0
2    C   95.0
1    B    NaN

In [7]:
indexed = df.set_index('name')
print('Rows by index:')
display(indexed.sort_index())
print('Columns by label:')
display(df.sort_index(axis=1))

Rows by index:

      department  score  experience    city
name
Asha          IT     88           3  Indore
Ishan         IT     88           1   Delhi
Kabir      Sales     74           7   Delhi
Meera         IT     95           2  Indore
Ravi       Sales     74           5    Pune
Zoya          HR     91           4    Pune

Columns by label:

     city department  experience   name  score
0  Indore         IT           3   Asha     88
1    Pune      Sales           5   Ravi     74
2  Indore         IT           2  Meera     95
3   Delhi      Sales           7  Kabir     74
4    Pune         HR           4   Zoya     91
5   Delhi         IT           1  Ishan     88

## 5. Ranking and ties

In [8]:
scores = pd.Series([90, 80, 90, 70], index=['Asha', 'Ravi', 'Meera', 'Kabir'])
print('Average:', scores.rank(ascending=False).to_dict())
print('Min:', scores.rank(ascending=False, method='min').to_dict())
print('Dense:', scores.rank(ascending=False, method='dense').to_dict())

Average: {'Asha': 1.5, 'Ravi': 3.0, 'Meera': 1.5, 'Kabir': 4.0}
Min: {'Asha': 1.0, 'Ravi': 3.0, 'Meera': 1.0, 'Kabir': 4.0}
Dense: {'Asha': 1.0, 'Ravi': 2.0, 'Meera': 1.0, 'Kabir': 3.0}

## 6. Rank within each department

In [9]:
ranked = df.copy()
ranked['department_rank'] = ranked.groupby('department')['score'].rank(ascending=False, method='dense')
ranked.sort_values(['department', 'department_rank', 'name'])

    name department  score  experience    city  department_rank
4   Zoya         HR     91           4    Pune              1.0
2  Meera         IT     95           2  Indore              1.0
0   Asha         IT     88           3  Indore              2.0
5  Ishan         IT     88           1   Delhi              2.0
3  Kabir      Sales     74           7   Delhi              1.0
1   Ravi      Sales     74           5    Pune              1.0

## 7. Top-N and bottom-N

In [10]:
print('Top three scores:')
display(df.nlargest(3, 'score'))
print('Two least experienced:')
display(df.nsmallest(2, 'experience'))

Top three scores:

    name department  score  experience    city
2  Meera         IT     95           2  Indore
4   Zoya         HR     91           4    Pune
0   Asha         IT     88           3  Indore

Two least experienced:

    name department  score  experience    city
5  Ishan         IT     88           1   Delhi
2  Meera         IT     95           2  Indore

## 8. Ordered categories

In [11]:
priority_order = pd.CategoricalDtype(categories=['Low', 'Medium', 'High'], ordered=True)
priorities = pd.DataFrame({'task': ['T1', 'T2', 'T3'], 'priority': pd.Series(['High', 'Low', 'Medium'], dtype=priority_order)})
priorities.sort_values('priority')

  task priority
1   T2      Low
2   T3   Medium
0   T1     High

## 9. Sort and reset index

In [12]:
df.sort_values(['score', 'experience'], ascending=[False, True], ignore_index=True)

    name department  score  experience    city
0  Meera         IT     95           2  Indore
1   Zoya         HR     91           4    Pune
2  Ishan         IT     88           1   Delhi
3   Asha         IT     88           3  Indore
4   Ravi      Sales     74           5    Pune
5  Kabir      Sales     74           7   Delhi

## Key takeaways

- Use `sort_values()` for data values and `sort_index()` for labels.
- Use `rank(ascending=False)` when the highest value should rank first.
- Select a tie method deliberately, and use `groupby().rank()` for within-group ranks.
- Sort before using `head()` when you mean top or bottom records.